# Generated by Django 3.1.1 on 2021-02-08 13:45

import consultant.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone_no', models.CharField(max_length=10, validators=[consultant.models.phone_validator])),
                ('email_id', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('ratings', models.FloatField()),
                ('number_of_reviews', models.IntegerField()),
                ('number_of_customers', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
                ('type_of_consultant', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultant_details',
            },
        ),
        migrations.CreateModel(
            name='ConsutancyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=150)),
                ('category_description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'consultancy_type',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(max_length=150)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.consultant')),
            ],
        ),
    ]
