# Generated by Django 3.1.1 on 2021-02-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='consultant_portfolio',
        ),
    ]
