# Generated by Django 3.1.1 on 2021-02-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='last_name',
        ),
    ]
