# Generated by Django 2.2.12 on 2021-03-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
