# Generated by Django 2.2.12 on 2021-03-02 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0002_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(default='', max_length=150)),
                ('portfolio_description', models.CharField(max_length=150)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.Consultant')),
            ],
            options={
                'db_table': 'consultant_portfolio',
            },
        ),
    ]
