# Generated by Django 3.1.1 on 2021-02-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0003_auto_20210217_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='state',
        ),
    ]
