# Generated by Django 3.1.1 on 2021-03-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0004_auto_20210302_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
