# Generated by Django 3.1.1 on 2021-03-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0006_auto_20210326_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='lat',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='long',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
