# Generated by Django 3.1.1 on 2021-03-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0008_auto_20210326_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='country',
            field=models.CharField(max_length=150),
        ),
    ]
