# Generated by Django 3.1.1 on 2021-02-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultee',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='consultee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='consultee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='consultee',
            name='state',
        ),
        migrations.AlterModelTable(
            name='consultee',
            table='consultee_details',
        ),
    ]
