# Generated by Django 3.1.1 on 2021-02-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultant', '__first__'),
        ('consultee', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_stamp', models.DateTimeField()),
                ('remark', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=150, unique=True)),
                ('country_description', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'countries_list',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_stamp', models.DateTimeField()),
                ('remark', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'slot',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=150, unique=True)),
                ('state_description', models.CharField(blank=True, max_length=250)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.country')),
            ],
            options={
                'db_table': 'states_list',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=250)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.consultant')),
                ('consultee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultee.consultee')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=150, unique=True)),
                ('city_description', models.CharField(blank=True, max_length=250)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.state')),
            ],
            options={
                'db_table': 'cities_list',
            },
        ),
    ]
