# Generated by Django 3.1.1 on 2021-02-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210208_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=150)),
                ('country_description', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'countries_list',
            },
        ),
    ]
