# Generated by Django 3.1.1 on 2021-02-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
