# Generated by Django 3.1.1 on 2021-02-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20210223_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=150, unique=True)),
                ('state_description', models.CharField(blank=True, max_length=250)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.country')),
            ],
            options={
                'db_table': 'states_list',
            },
        ),
    ]
