# Generated by Django 3.1.1 on 2021-02-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=150, unique=True)),
                ('city_description', models.CharField(blank=True, max_length=250)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.state')),
            ],
            options={
                'db_table': 'cities_list',
            },
        ),
    ]
