# Generated by Django 3.1.1 on 2021-03-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_userrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
