# Generated by Django 3.1.1 on 2021-03-26 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0005_consultant_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0008_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_stamp', models.DateTimeField()),
                ('remark', models.CharField(max_length=250)),
                ('consultant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultant.consultant')),
                ('consultee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
